name: animation_pool
description: animation_pool is a package that allows you to implement a pool of reused animations, without recreating them
version: 0.0.1
homepage:
repository: 

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
